### ISSUE TITLE
Input message is shifted on the left when trying to delete a personal shortcut

### ISSUE THREAD

**Issue by DrUm78** [FunKey-Project/gmenu2x#3]
Input message is shifted when trying to delete a shortcut that the user created. Indeed, "No (B) Yes (A)" is shifted on the left of the screen. It can be more or less shifted depending on the font size used.
Tested on firmware 2.1.1 beta.

See attached screenshot:
![IMG_0039](https://user-images.githubusercontent.com/46139740/115109264-fdeb2180-9f74-11eb-8573-cba1e216b141.PNG)

Steps to reproduce:
1. Create any GMenu2X shortcut
2. Press Fn button and select "Delete"
3. Notice that "No (B) Yes (A)" is shifted on the left of the screen

**Comment by Michel-FK** [comment]
Fixed with commit https://github.com/FunKey-Project/gmenu2x/commit/1b1c2512b1daa41bd49df90624825bf32c52064b

**Comment by DrUm78** [comment]
Fixed and verified!
